#!/bin/zsh

usage () {
    cat <<EOF
Bitwarden using fzf

Usage
    bwf [options]

OPTIONS
    -x, --clipboard insert into clipbaord (default)
    -h, --help      display this help message
    -p, --password  print password to stdout
    -u, --username  print username to stdout

CLIPBOARD
    Uses xclip to paste username into clipboard and
    password to primary selection.
EOF
}

fzf-command () {
    if [[ -v TMUX ]]; then
        fzf-tmux -p 40% -w 30% $* 
    else
        fzf --height=25% --layout=reverse $* 
    fi
}

get-item () {
    bw list items | jq '.[] | .name' --raw-output | fzf-command
}

get-user () {
    if [ "$#" -gt 0 ]; then
        bw get username $*
    else
        bw get username $(get-item)
    fi
}

get-password () {
    if [ "$#" -gt 0 ]; then
        bw get password $*
    else
        bw get password $(get-item)
    fi
}

insert-clipboard () {
    local item=$(get-item)
    get-user $item | xclip -selection clipboard -i 
    get-password $item | xclip -selection primary
}

while [[ "$#" -gt 0 ]]; do
    case $1 in
        -h|--help) usage; exit 0;;
        -p|--password) get-password; exit 0;;
        -u|--username) get-user; exit 0;;
        -x|--clipboard) insert-clipboard; exit 0;;
        *) echo "Unknown argument: $1"; exit 1;;
    esac
    shift
done
insert-clipboard
