#!/bin/zsh

allItems=""

usage () {
    cat <<EOF
Bitwarden using fzf

Usage
    bwf [options]

OPTIONS
    -x, --clipboard insert into clipbaord (default)
    -h, --help      display this help message
    -p, --password  print password to stdout
    -u, --username  print username to stdout

CLIPBOARD
    Uses xclip to paste username into clipboard and
    password to primary selection.
EOF
}

fzf-command () {
    if [[ -v TMUX ]]; then
        # Edit this if you use tmux and want to change the appearance
        fzf-tmux -p 40% -w 30% $* 
    else
        # Edit this if you don't use tmux and want to change the appearance
        fzf --height=25% --layout=reverse $* 
    fi
}

get-item () {
    jq -r '.[] | .name' <<< "${allItems}" | fzf-command
}

get-user () {
    if [ "$#" -gt 0 ]; then
        jq -r 'map(select(.name == "'"$*"'")) | .[] | .login.username' <<< "${allItems}"
    else
        jq -r 'map(select(.name == "'"$(get-item)"'")) | .[] .login.username' <<< "${allItems}"
    fi
}

get-password () {
    if [ "$#" -gt 0 ]; then
        # bw get password $*
        jq -r 'map(select(.name == "'"$*"'")) | .[] | .login.password' <<< "${allItems}"
    else
        jq -r 'map(select(.name == "'"$(get-item)"'")) | .[] | .login.password' <<< "${allItems}"
    fi
}

insert-clipboard () {
    local item
    if [ "$#" -gt 0 ]; then
        item=$*
    else
        echo "here"
        item=$(get-item)
    fi
    get-user $item | xclip -selection clipboard -i 
    get-password $item | xclip -selection primary
}

allItems=$(bw list items)
clipboard="1"
item=$(get-item)
while [[ "$#" -gt 0 ]]; do
    case $1 in
        -h|--help) usage; exit 0;;
        -p|--password) 
            get-password $item
            clipboard="0"
            ;;
        -u|--username)
            get-user $item
            clipboard="0"
            ;;
        -x|--clipboard)
            insert-clipboard $item
            clipboard="0"
            ;;
        *) echo "Unknown argument: $1"; exit 1;;
    esac
    shift
done
if [ $clipboard -gt 0 ];
then
    insert-clipboard $item
fi

